name: Build

on: 
  push:
    branches: [ main ]  # Adjust the branch name if needed
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest  
    container: shinchven/node:20-build  # Use your custom image

    steps:
      - uses: actions/checkout@v3  # Check out the repository 
      - name: Build and Release
        run: |
          cd app  # Move into the 'app' directory
          npm install
          npm run release
