name: Build

on: 
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  build_test_package:
    runs-on: ubuntu-latest  
    container: shinchven/node:20-build 

    steps:
      - uses: actions/checkout@v4
      - name: Build and Release
        run: |
          cd app  
          npm install
          npm run release
          rm -rf node_modules  # Remove node_modules
          cd ..

      - name: Create Package Archive
        run: |
          mv app druid
          tar -cvzf druid.tar.gz druid 
          pwd
          ls -lh

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: druid
          path: druid.tar.gz
